version: '3'
 
services: 
  grafana: 
    image: grafana/grafana 
    container_name: grafana 
    networks: 
      - grafana 
    environment: 
      - GF_PATHS_DATA=/var/lib/grafana 
    ports: 
      - 3000:3000 
    volumes: 
      - ./data:/var/lib/grafana 
networks: 
  grafana: {}